language: node_js
node_js:
  - "8.6"
  - "8.7"
  - "stable"
sudo: false
os:
  - linux
  - osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi

script:
  - npm test
  - npm install prebuild-ci
  - ./node_modules/.bin/prebuild-ci
